version: '2'
services:
  doorcontrol:
    build:
      context: app/web
      dockerfile: Dockerfile
      args:
        VIRTUAL_ENV: /opt/venv
    ports:
      - 3000:3000
    environment:
      DOORMANAGER_HOST: doormanager
      PORT: 3000
    labels:
      - traefik.enable=true
      - traefik.http.routers.doorcontrol.entrypoints=http
      - traefik.http.routers.doorcontrol.rule=Host(`doorcontrol.localhost`)
    command: npm start
  doormanager:
    privileged: true
    build:
      context: app/doormanager
      dockerfile: Dockerfile
      args:
        VIRTUAL_ENV: /opt/venv
    expose:
      - 5555
    ports:
      - 1883:1883
    labels:
      - traefik.enable=true
      - traefik.http.routers.doormanager.entrypoints=http
      - traefik.http.routers.doormanager.rule=PathPrefix(`/doormanager`)
      # - traefik.http.routers.doormanager.rule=Host(`doormanager.localhost`)
      - traefik.http.middlewares.strip-doormanager.stripprefix.prefixes=/doormanager
      - traefik.http.services.doormanager.loadbalancer.server.port=5555
      # - traefik.http.routers.doormanager.service=doormanager
    command: gunicorn main:app -b 0.0.0.0:5555 -k uvicorn.workers.UvicornWorker
  traefik:
    image: traefik:latest
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - --api.insecure=true
      - --entrypoints.web.address=:80
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.endpoint=unix:///var/run/balena.sock
    ports:
      - 80:80
      - 8080:8080
    labels:
      - io.balena.features.balena-socket= true
