version: '2'
services:

  doorcontrol:
    build:
      context: app/web
      dockerfile: Dockerfile
      args:
        VIRTUAL_ENV: "/opt/venv"
    ports:
      - "3000:3000"
    environment:
      DOORMANAGER_GRPC_HOST: doormanager
      DOORMANAGER_GRPC_PORT: 5000
    command: npm start

  # anvil_server:
  #   privileged: true
  #   build:
  #     context: app/web
  #     dockerfile: Dockerfile
  #     args:
  #       VIRTUAL_ENV: "/opt/venv"
  #   # ports:
  #   # #   # - "3030:3030"
  #   # #   # - "8080:8080"
  #   #   - "8443:443/tcp"
  #   #   - "8080:80/tcp"
  #   environment:
  #     DOORMANAGER_GRPC_HOST: doormanager
  #     DOORMANAGER_GRPC_PORT: 5000
  #   volumes:
  #     - 'anvil-data:/anvil-data'
  #   # command: balena-idle
  #   # command: anvil-app-server --data-dir /anvil-data --app web
  #   command: --app web
  #   networks:
  #     - backend
  #     - host

  doormanager:
    privileged: true
    build:
      context: app/doormanager
      dockerfile: Dockerfile
      args:
        VIRTUAL_ENV: "/opt/venv"
    ports:
      - '1883:1883'
      - '5000:5000'
    environment:
      DOORMANAGER_GRPC_PORT: 5000
    command: python3 doormanager/main.py

  # mail:
  #   image: bytemark/smtp
  #   ports:
  #   - '587:587'

# volumes:
#   anvil-data: