version: '2'
services:

  traefik:
    build:
      context: traefik
      dockerfile: Dockerfile
    volumes:
      - certs:/var/certs
    ports:
      - 80:80/tcp
      - 443:443/tcp
      - 8081:8080/tcp
    labels:
      - io.balena.features.balena-socket=true

  doorcontrol:
    build:
      context: app/web
      dockerfile: Dockerfile.doorcontrol
    expose:
      - 3000
    environment:
      DOORMANAGER_HOST: doormanager
      PORT: 3000
    command: npm start

  
  doormonitor:
    build:
      context: app/web
      dockerfile: Dockerfile.doormonitor
    expose:
      - 3000
    environment:
      DOORMANAGER_HOST: doormanager
      PORT: 3000
    command: npm start

  doormanager:
    privileged: true
    build:
      context: app/doormanager
      dockerfile: Dockerfile
      args:
        VIRTUAL_ENV: /opt/venv
    expose:
      - 5555
    ports:
      - 1883:1883
    depends_on: 
      - lock_db
    # command: gunicorn main:create_app() -b 0.0.0.0:5555 -k uvicorn.workers.UvicornWorker
    command: gunicorn main:app -b 0.0.0.0:5555 -k uvicorn.workers.UvicornWorker
    
  unifi-controller:
    build:
      context: unifi
      dockerfile: Dockerfile
    environment:
      PUID: 1000
      PGID: 1000
      # - MEM_LIMIT=1024M #optional
    volumes:
      - unifi-config:/config
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 1900:1900/udp #optional
      - 8080:8080
      - 8843:8843 #optional
      - 8443:8443 #optional
      - 8880:8880 #optional
      - 6789:6789 #optional
      - 5514:5514/udp #optional
    # expose:
    #   - 8443
    # labels:
    #   traefik.enable: true
    #   traefik.http.routers.unifi.entrypoints: websecure
    #   # - traefik.http.routers.unifi.rule: PathPrefix(`/unifi{regex:$$|/.*}`)
    #   # - traefik.http.routers.unifi.rule:  Host(`unifi.$DOMAIN`) || PathPrefix(`/unifi{regex:$$|/.*}
    #   traefik.http.routers.unifi.rule:  Host(`unifi.${DOMAIN}`)
    #   # - traefik.http.routers.unifi.tls: true
    #   traefik.http.routers.unifi.tls.certresolver: duckdns
    #   traefik.http.routers.unifi.middlewares: unifi-stripprefix
    #   traefik.http.middlewares.unifi-stripprefix.stripprefix.prefixes: /unifi
    #   traefik.http.services.unifi.loadbalancer.server.port: 8443

  lock_db:
    build:
      context: db
      dockerfile: Dockerfile.db
    volumes:
      - 'app-db-data:/var/lib/postgresql/data/pgdata'
    # env_file:
    #   - postgresql/database.env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    # deploy:
    #   placement:
    #     constraints:
    #       - 'node.labels.${STACK_NAME?Variable not set}.app-db-data == true'
  
 
  # mqtt:
  #   image: panuwitp/mosquitto-arm
  #   ports:
  #     - "1883:1883"

# networks:
#   mqtt:
#   web:

volumes:
  certs:
  unifi-config: 
  app-db-data:

# networks:
#   traefik-public:
#     external: '${TRAEFIK_PUBLIC_NETWORK_IS_EXTERNAL-false}'