Main:
    pin: 19
    command_topic: "door/1/cmd"
    state_topic: "door/1/state"
    state: "Unknown"
Garage:
    pin: 26
    command_topic: "door/2/cmd"
    state_topic: "door/2/state"
    state: "Unknown"
Workshop:
    pin: 20
    command_topic: "door/3/cmd"
    state_topic: "door/3/state"
    state: "Unknown"
