
FROM python:3.8.9 as builder

ARG VIRTUAL_ENV


RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

RUN pip3 install --upgrade pip
RUN pip3 install \
    setuptools \
    wheel 


COPY requirements.txt requirements.txt

RUN pip3 install --ignore-installed -r requirements.txt


FROM python:3.8.9

ARG VIRTUAL_ENV
ARG DOMAIN
ARG CERTRESOLVER

ARG POSTGRES_SERVER
ARG POSTGRES_USER
ARG POSTGRES_PASSWORD
ARG POSTGRES_DB

ENV POSTGRES_SERVER=$POSTGRES_SERVER
ENV POSTGRES_USER=$POSTGRES_USER
ENV POSTGRES_PASSWORD=$POSTGRES_PASSWORD
ENV POSTGRES_DB=$POSTGRES_DB


COPY --from=builder $VIRTUAL_ENV $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"



RUN : \
    && apt update \
    && DEBIAN_FRONTEND=noninteractive apt install -y --no-install-recommends \
    libpq5 \
    && apt-get clean \
        && rm -rf /var/lib/apt/lists/* \
        && :

WORKDIR /app

COPY src/ .

RUN echo 'alias run="gunicorn main:app -b 0.0.0.0:5555 -k uvicorn.workers.UvicornWorker"' >> ~/.bashrc
# ENV UDEV=1

