# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/doormanager.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/doormanager.proto',
  package='doormanager',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x18protos/doormanager.proto\x12\x0b\x64oormanager\"\r\n\x0bTestRequest\"\x18\n\tTestReply\x12\x0b\n\x03rep\x18\x01 \x01(\t\"\x1f\n\x11UnlockDoorRequest\x12\n\n\x02nr\x18\x01 \x01(\x05\"\x11\n\x0fUnlockDoorReply\"\x1d\n\x0fLockDoorRequest\x12\n\n\x02nr\x18\x01 \x01(\x05\"\x0f\n\rLockDoorReply\"\x1f\n\x11ToggleDoorRequest\x12\n\n\x02nr\x18\x01 \x01(\x05\"\x11\n\x0fToggleDoorReply\"\x15\n\x13GetDoorStateRequest\".\n\x11GetDoorStateReply\x12\n\n\x02nr\x18\x01 \x01(\x05\x12\r\n\x05state\x18\x02 \x01(\x05\x32\x81\x03\n\x0b\x44oorManager\x12:\n\x04Test\x12\x18.doormanager.TestRequest\x1a\x16.doormanager.TestReply\"\x00\x12L\n\nUnlockDoor\x12\x1e.doormanager.UnlockDoorRequest\x1a\x1c.doormanager.UnlockDoorReply\"\x00\x12\x46\n\x08LockDoor\x12\x1c.doormanager.LockDoorRequest\x1a\x1a.doormanager.LockDoorReply\"\x00\x12L\n\nToggleDoor\x12\x1e.doormanager.ToggleDoorRequest\x1a\x1c.doormanager.ToggleDoorReply\"\x00\x12R\n\x0cGetDoorState\x12 .doormanager.GetDoorStateRequest\x1a\x1e.doormanager.GetDoorStateReply\"\x00\x62\x06proto3'
)




_TESTREQUEST = _descriptor.Descriptor(
  name='TestRequest',
  full_name='doormanager.TestRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=54,
)


_TESTREPLY = _descriptor.Descriptor(
  name='TestReply',
  full_name='doormanager.TestReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='rep', full_name='doormanager.TestReply.rep', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=80,
)


_UNLOCKDOORREQUEST = _descriptor.Descriptor(
  name='UnlockDoorRequest',
  full_name='doormanager.UnlockDoorRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='nr', full_name='doormanager.UnlockDoorRequest.nr', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=113,
)


_UNLOCKDOORREPLY = _descriptor.Descriptor(
  name='UnlockDoorReply',
  full_name='doormanager.UnlockDoorReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=115,
  serialized_end=132,
)


_LOCKDOORREQUEST = _descriptor.Descriptor(
  name='LockDoorRequest',
  full_name='doormanager.LockDoorRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='nr', full_name='doormanager.LockDoorRequest.nr', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=134,
  serialized_end=163,
)


_LOCKDOORREPLY = _descriptor.Descriptor(
  name='LockDoorReply',
  full_name='doormanager.LockDoorReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=165,
  serialized_end=180,
)


_TOGGLEDOORREQUEST = _descriptor.Descriptor(
  name='ToggleDoorRequest',
  full_name='doormanager.ToggleDoorRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='nr', full_name='doormanager.ToggleDoorRequest.nr', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=182,
  serialized_end=213,
)


_TOGGLEDOORREPLY = _descriptor.Descriptor(
  name='ToggleDoorReply',
  full_name='doormanager.ToggleDoorReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=215,
  serialized_end=232,
)


_GETDOORSTATEREQUEST = _descriptor.Descriptor(
  name='GetDoorStateRequest',
  full_name='doormanager.GetDoorStateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=234,
  serialized_end=255,
)


_GETDOORSTATEREPLY = _descriptor.Descriptor(
  name='GetDoorStateReply',
  full_name='doormanager.GetDoorStateReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='nr', full_name='doormanager.GetDoorStateReply.nr', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='state', full_name='doormanager.GetDoorStateReply.state', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=257,
  serialized_end=303,
)

DESCRIPTOR.message_types_by_name['TestRequest'] = _TESTREQUEST
DESCRIPTOR.message_types_by_name['TestReply'] = _TESTREPLY
DESCRIPTOR.message_types_by_name['UnlockDoorRequest'] = _UNLOCKDOORREQUEST
DESCRIPTOR.message_types_by_name['UnlockDoorReply'] = _UNLOCKDOORREPLY
DESCRIPTOR.message_types_by_name['LockDoorRequest'] = _LOCKDOORREQUEST
DESCRIPTOR.message_types_by_name['LockDoorReply'] = _LOCKDOORREPLY
DESCRIPTOR.message_types_by_name['ToggleDoorRequest'] = _TOGGLEDOORREQUEST
DESCRIPTOR.message_types_by_name['ToggleDoorReply'] = _TOGGLEDOORREPLY
DESCRIPTOR.message_types_by_name['GetDoorStateRequest'] = _GETDOORSTATEREQUEST
DESCRIPTOR.message_types_by_name['GetDoorStateReply'] = _GETDOORSTATEREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TestRequest = _reflection.GeneratedProtocolMessageType('TestRequest', (_message.Message,), {
  'DESCRIPTOR' : _TESTREQUEST,
  '__module__' : 'protos.doormanager_pb2'
  # @@protoc_insertion_point(class_scope:doormanager.TestRequest)
  })
_sym_db.RegisterMessage(TestRequest)

TestReply = _reflection.GeneratedProtocolMessageType('TestReply', (_message.Message,), {
  'DESCRIPTOR' : _TESTREPLY,
  '__module__' : 'protos.doormanager_pb2'
  # @@protoc_insertion_point(class_scope:doormanager.TestReply)
  })
_sym_db.RegisterMessage(TestReply)

UnlockDoorRequest = _reflection.GeneratedProtocolMessageType('UnlockDoorRequest', (_message.Message,), {
  'DESCRIPTOR' : _UNLOCKDOORREQUEST,
  '__module__' : 'protos.doormanager_pb2'
  # @@protoc_insertion_point(class_scope:doormanager.UnlockDoorRequest)
  })
_sym_db.RegisterMessage(UnlockDoorRequest)

UnlockDoorReply = _reflection.GeneratedProtocolMessageType('UnlockDoorReply', (_message.Message,), {
  'DESCRIPTOR' : _UNLOCKDOORREPLY,
  '__module__' : 'protos.doormanager_pb2'
  # @@protoc_insertion_point(class_scope:doormanager.UnlockDoorReply)
  })
_sym_db.RegisterMessage(UnlockDoorReply)

LockDoorRequest = _reflection.GeneratedProtocolMessageType('LockDoorRequest', (_message.Message,), {
  'DESCRIPTOR' : _LOCKDOORREQUEST,
  '__module__' : 'protos.doormanager_pb2'
  # @@protoc_insertion_point(class_scope:doormanager.LockDoorRequest)
  })
_sym_db.RegisterMessage(LockDoorRequest)

LockDoorReply = _reflection.GeneratedProtocolMessageType('LockDoorReply', (_message.Message,), {
  'DESCRIPTOR' : _LOCKDOORREPLY,
  '__module__' : 'protos.doormanager_pb2'
  # @@protoc_insertion_point(class_scope:doormanager.LockDoorReply)
  })
_sym_db.RegisterMessage(LockDoorReply)

ToggleDoorRequest = _reflection.GeneratedProtocolMessageType('ToggleDoorRequest', (_message.Message,), {
  'DESCRIPTOR' : _TOGGLEDOORREQUEST,
  '__module__' : 'protos.doormanager_pb2'
  # @@protoc_insertion_point(class_scope:doormanager.ToggleDoorRequest)
  })
_sym_db.RegisterMessage(ToggleDoorRequest)

ToggleDoorReply = _reflection.GeneratedProtocolMessageType('ToggleDoorReply', (_message.Message,), {
  'DESCRIPTOR' : _TOGGLEDOORREPLY,
  '__module__' : 'protos.doormanager_pb2'
  # @@protoc_insertion_point(class_scope:doormanager.ToggleDoorReply)
  })
_sym_db.RegisterMessage(ToggleDoorReply)

GetDoorStateRequest = _reflection.GeneratedProtocolMessageType('GetDoorStateRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETDOORSTATEREQUEST,
  '__module__' : 'protos.doormanager_pb2'
  # @@protoc_insertion_point(class_scope:doormanager.GetDoorStateRequest)
  })
_sym_db.RegisterMessage(GetDoorStateRequest)

GetDoorStateReply = _reflection.GeneratedProtocolMessageType('GetDoorStateReply', (_message.Message,), {
  'DESCRIPTOR' : _GETDOORSTATEREPLY,
  '__module__' : 'protos.doormanager_pb2'
  # @@protoc_insertion_point(class_scope:doormanager.GetDoorStateReply)
  })
_sym_db.RegisterMessage(GetDoorStateReply)



_DOORMANAGER = _descriptor.ServiceDescriptor(
  name='DoorManager',
  full_name='doormanager.DoorManager',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=306,
  serialized_end=691,
  methods=[
  _descriptor.MethodDescriptor(
    name='Test',
    full_name='doormanager.DoorManager.Test',
    index=0,
    containing_service=None,
    input_type=_TESTREQUEST,
    output_type=_TESTREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='UnlockDoor',
    full_name='doormanager.DoorManager.UnlockDoor',
    index=1,
    containing_service=None,
    input_type=_UNLOCKDOORREQUEST,
    output_type=_UNLOCKDOORREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='LockDoor',
    full_name='doormanager.DoorManager.LockDoor',
    index=2,
    containing_service=None,
    input_type=_LOCKDOORREQUEST,
    output_type=_LOCKDOORREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ToggleDoor',
    full_name='doormanager.DoorManager.ToggleDoor',
    index=3,
    containing_service=None,
    input_type=_TOGGLEDOORREQUEST,
    output_type=_TOGGLEDOORREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetDoorState',
    full_name='doormanager.DoorManager.GetDoorState',
    index=4,
    containing_service=None,
    input_type=_GETDOORSTATEREQUEST,
    output_type=_GETDOORSTATEREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DOORMANAGER)

DESCRIPTOR.services_by_name['DoorManager'] = _DOORMANAGER

# @@protoc_insertion_point(module_scope)
