# # to enable this proxy service set the following environment variables
# # either via docker-compose.yml or the Balena Application Dashboard
# #
# #  [HOMEASSISTANT_HOST]
# #   public domain or subdomain with dns A records pointing to your server or firewall
# #   example: homeassistant.example.com
# #
# #  [HOMEASSISTANT_SERVER]
# #   internal http server url to receive proxied traffic
# #   example: http://192.168.8.6:8123
# #
# [http]

# [http.routers]
# [http.routers.unifi]
# rule = "Host(`unifi.${DOMAIN}`)"
# service = "unifi-controller"
# middlewares = ["hsts-header"]

# # middlewares = ["hsts-header", "ip-allowlist"]
# [http.routers.unifi.tls]
# certresolver = "${CERTRESOLVER}"

# [http.services]
# [http.services.unifi.loadBalancer.server]
# port = 8080



