# FROM balenalib/raspberrypi3-debian:stretch-build as client_builder

# ENV FLUTTER_CHANNEL=stable
# ENV FLUTTER_VERSION=2.0.1-${FLUTTER_CHANNEL}
# ENV FLUTTER_TAR=flutter_linux_${FLUTTER_VERSION}.tar.xz

# RUN apt-get update -y
# RUN apt-get upgrade -y

# RUN install_packages \
#   curl \
#   git \
#   unzip \
#   wget \
#   xz-utils \
#   apt-transport-https \
#   ca-certificates \
#   gnupg


# RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -

# WORKDIR /opt
# RUN wget https://storage.googleapis.com/flutter_infra/releases/stable/linux/${FLUTTER_TAR}
# RUN tar xf ${FLUTTER_TAR}
# ENV PATH="/opt/flutter/bin:$PATH"

# VOLUME /app
# WORKDIR /app

# COPY doorcontrol .

# RUN flutter build web


FROM node:12-alpine


WORKDIR /usr/src/app

COPY server/package*.json ./

RUN JOBS=MAX npm install --production --unsafe-perm && npm cache verify && rm -rf /tmp/*


COPY server ./
COPY doorcontrol/build/web app/